/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PAT_UI;

import PAT_Backend.DataBaseManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jcj
 */
public class PopulateJComponents extends javax.swing.JFrame
{

    /**
     * Creates new form PopulateJComponents
     */
    public PopulateJComponents()
    {
        initComponents();
        
        ArrayList<String> names = getNamesList();
        
/*  to get from inserted values        
        //jlist:
        DefaultListModel <String> listmodel = new DefaultListModel<>();
        listmodel.addAll(names);
        studentList.setModel(listmodel);
        
        //combobox:
        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel();
        comboModel.addAll(names);
        studentComboBox.setModel(comboModel);
        
        //table:
        String [] collumnNames = {"Name", "Surname", "Age", "Grade"};
        String [][] data = { {"John", "Person", "15", "10"},
                                        {"Peter", "Person", "12", "6"},
                                        {"Cliff", "Bartholomew", "18", "12"},
                                        {"Nar", "Abbot", "16", "11"}
                                       };
        */
        String [] collumnNames = {"ID", "Name", "Surname", "Age"};
        String [][] data = getStudentsArray();
        
        
        DefaultTableModel tableModel = new DefaultTableModel(data, collumnNames);
        
        studentsTable.setModel(tableModel);
    }
    private String[][] getStudentsArray()
    {
        String [][] data = new String [10][4];
        
        DataBaseManager bd = new DataBaseManager();
        try
        {
            ResultSet students = bd.query("Select * from peopleTable_testUI;");
            
            int currRow = 0;
            while (students.next())
            {
//                data[currRow][1] = (students.getString(1));
//                data[currRow][2] = (students.getString(2));
//                data[currRow][3] = (students.getString(3));
//                data[currRow][4] = (students.getString(4));
                
                for (int i = 1; i < 5; i++)
                {
                    data[currRow][i-1] = (students.getString(i));
                }
                
                currRow ++;
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(PopulateJComponents.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return data;
    }
    private ArrayList<String> getNamesList()
    {
        ArrayList<String> names = new ArrayList<>();
        
        DataBaseManager bd = new DataBaseManager();
        
        try
        {
            ResultSet students = bd.query("Select \'name\' from peopleTable_testUI;");
            
            while (students.next())
            {
                names.add(students.getString(1));
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(PopulateJComponents.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return names;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList<>();
        studentComboBox = new javax.swing.JComboBox<>();
        comboBoxLabel = new javax.swing.JLabel();
        listLabel = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Name", "Surname", "Age", "Grade"
            }
        ));
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                studentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 210));

        studentList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        studentList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                studentListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studentList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 150));

        studentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        studentComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                studentComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(studentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        comboBoxLabel.setText("jLabel1");
        jPanel1.add(comboBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        listLabel.setText("jLabel2");
        jPanel1.add(listLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        tableLabel.setText("jLabel1");
        jPanel1.add(tableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_studentListMouseClicked
    {//GEN-HEADEREND:event_studentListMouseClicked
        // TODO add your handling code here:
        listLabel.setText(studentList.getSelectedValue());
    }//GEN-LAST:event_studentListMouseClicked

    private void studentComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_studentComboBoxActionPerformed
    {//GEN-HEADEREND:event_studentComboBoxActionPerformed
        // TODO add your handling code here:
        comboBoxLabel.setText((String)studentComboBox.getSelectedItem());
    }//GEN-LAST:event_studentComboBoxActionPerformed

    private void studentsTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_studentsTableMouseClicked
    {//GEN-HEADEREND:event_studentsTableMouseClicked
        // TODO add your handling code here:
        tableLabel.setText( (String) studentsTable.getValueAt(studentsTable.getSelectedRow(), 0));
    }//GEN-LAST:event_studentsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PopulateJComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PopulateJComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PopulateJComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PopulateJComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PopulateJComponents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comboBoxLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listLabel;
    private javax.swing.JComboBox<String> studentComboBox;
    private javax.swing.JList<String> studentList;
    private javax.swing.JTable studentsTable;
    private javax.swing.JLabel tableLabel;
    // End of variables declaration//GEN-END:variables
}
